<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>xrbit_sensors</name>
  <version>0.0.1</version>
  <description>C++ Hardware Interface for SICK and ifm Sensors</description>
  <maintainer email="rakesh@todo.todo">rakesh</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>xrbit_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
