/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : XRbit Sorter MCU Firmware (STM32F407)
  * @description    : Non-blocking stepper motor controller over USB Virtual COM.
  *                   Parses 5-byte binary protocol from ROS 2 and drives TMC2209.
  ******************************************************************************
  */

#include "main.h"
/* Note: In STM32CubeIDE, you must enable USB_DEVICE as "Communication Device Class (Virtual Port Com)" */
// #include "usbd_cdc_if.h" 

// --------------------------------------------------------
// HARDWARE PIN DEFINITIONS (Matched to Architecture Rev 3.0)
// --------------------------------------------------------
// Conveyor Motor
#define CONV_STEP_PIN  GPIO_PIN_0  // PA0
#define CONV_DIR_PIN   GPIO_PIN_1  // PA1
#define CONV_PORT      GPIOA

// Sorting Arm 1
#define ARM1_STEP_PIN  GPIO_PIN_6  // PA6
#define ARM1_DIR_PIN   GPIO_PIN_7  // PA7
#define ARM1_PORT      GPIOA

// Sorting Arm 2
#define ARM2_STEP_PIN  GPIO_PIN_6  // PB6
#define ARM2_DIR_PIN   GPIO_PIN_7  // PB7
#define ARM2_PORT      GPIOB

// --------------------------------------------------------
// STATE VARIABLES FOR INTERRUPT-DRIVEN MOTION
// --------------------------------------------------------
// Arm 1
volatile uint32_t arm1_target_steps = 0;
volatile uint32_t arm1_current_steps = 0;
volatile uint8_t  arm1_moving = 0;

// Arm 2
volatile uint32_t arm2_target_steps = 0;
volatile uint32_t arm2_current_steps = 0;
volatile uint8_t  arm2_moving = 0;

// Hardware Timer Handles (Auto-generated by CubeMX)
extern TIM_HandleTypeDef htim2; // Conveyor Speed (Continuous)
extern TIM_HandleTypeDef htim3; // Arm 1 Speed
extern TIM_HandleTypeDef htim4; // Arm 2 Speed

// --------------------------------------------------------
// 1. USB SERIAL PARSER (Runs when Jetson sends command)
// --------------------------------------------------------
/* 
 * This function is called from CDC_Receive_FS in usbd_cdc_if.c 
 * whenever the STM32 receives data over the USB cable.
 */
void Process_Sort_Command(uint8_t* buf, uint32_t len) {
    if (len < 5) return; // Ignore incomplete packets
    
    // Verify 5-Byte Protocol: [0xAA, ArmID, TrayID, Checksum, 0x55]
    if (buf[0] != 0xAA || buf[4] != 0x55) return; // Invalid Start/End bytes
    
    uint8_t arm_id = buf[1];
    uint8_t tray_id = buf[2];
    uint8_t chk = buf[3];
    
    if (chk != (uint8_t)(arm_id + tray_id)) return; // Checksum failed! Corrupted data.

    // Calculate required steps based on target tray
    // Assuming 1.8 deg motor, 16 microsteps = 3200 steps/rev. 
    // 200 steps = approx 22.5 degrees of arm rotation per tray.
    uint32_t steps_per_tray = 200; 

    // TRIGGER ARM 1
    if (arm_id == 1 && !arm1_moving) {
        HAL_GPIO_WritePin(ARM1_PORT, ARM1_DIR_PIN, GPIO_PIN_SET); // Set direction outwards
        arm1_target_steps = tray_id * steps_per_tray;
        arm1_current_steps = 0;
        arm1_moving = 1;
        HAL_TIM_Base_Start_IT(&htim3); // Start Timer 3 hardware interrupts
    } 
    
    // TRIGGER ARM 2
    else if (arm_id == 2 && !arm2_moving) {
        HAL_GPIO_WritePin(ARM2_PORT, ARM2_DIR_PIN, GPIO_PIN_SET); // Set direction outwards
        arm2_target_steps = (tray_id - 4) * steps_per_tray; // Trays 5-8 offset
        arm2_current_steps = 0;
        arm2_moving = 1;
        HAL_TIM_Base_Start_IT(&htim4); // Start Timer 4 hardware interrupts
    }
}

// --------------------------------------------------------
// 2. HARDWARE TIMER INTERRUPTS (The "Muscle")
// --------------------------------------------------------
/*
 * This runs automatically in the background thousands of times per second.
 * It provides perfectly spaced electrical pulses to the TMC2209 drivers.
 * Because it uses hardware timers, it NEVER blocks the main CPU.
 */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {
    
    // CONVEYOR BELT (Always running)
    if (htim->Instance == TIM2) {
        // Toggle the pin to create a square wave pulse
        HAL_GPIO_TogglePin(CONV_PORT, CONV_STEP_PIN);
    }
    
    // ARM 1 SORTING MOTION
    else if (htim->Instance == TIM3) {
        if (arm1_current_steps < (arm1_target_steps * 2)) { 
            // * 2 because 1 step requires a HIGH and LOW toggle
            HAL_GPIO_TogglePin(ARM1_PORT, ARM1_STEP_PIN);
            arm1_current_steps++;
        } else {
            // Target reached! Stop the timer.
            HAL_TIM_Base_Stop_IT(&htim3);
            arm1_moving = 0;
            // Note: In reality, you'd trigger a reverse motion here to return to home!
        }
    }
    
    // ARM 2 SORTING MOTION
    else if (htim->Instance == TIM4) {
        if (arm2_current_steps < (arm2_target_steps * 2)) {
            HAL_GPIO_TogglePin(ARM2_PORT, ARM2_STEP_PIN);
            arm2_current_steps++;
        } else {
            HAL_TIM_Base_Stop_IT(&htim4);
            arm2_moving = 0;
        }
    }
}

// --------------------------------------------------------
// 3. MAIN LOOP
// --------------------------------------------------------
int main(void) {
    HAL_Init();
    // SystemClock_Config(); // Auto-generated by CubeMX
    // MX_GPIO_Init();       // Auto-generated by CubeMX
    // MX_USB_DEVICE_Init(); // Auto-generated by CubeMX
    
    // Start Conveyor Belt immediately
    HAL_TIM_Base_Start_IT(&htim2); 

    while (1) {
        // The main loop is completely empty! 
        // 100% of the work is handled efficiently by USB and Timer Interrupts.
    }
}
